### PR TITLE
Update curseforge link

### PR DESCRIPTION
**Pull request by RainEffect**
That old curseforge link not work now.

### CODE REVIEW

**Comment by rubensworks** [comment]
The original link works for me though. What error do you see when you click on the original link?

**Comment by RainEffect** [comment]
Error image

**Comment by rubensworks** [comment]
Weird...
I tried on different browsers, and I don't have that problem here.

Is it a caching issue with you? Can you try a different browser?

**Comment by RainEffect** [comment]
I'm have been tried on another browser, maybe that reason was I live in China...

**Pull request closed without merging**
